<script src="{{ asset('/jqwidgets/jqxtabs.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxsplitter.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdata.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdata.export.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxlayout.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxribbon.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxpanel.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxexpander.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxscrollbar.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxbuttons.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxswitchbutton.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxinput.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtextarea.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxcheckbox.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxradiobutton.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxlistbox.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxnumberinput.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdropdownlist.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdropdownbutton.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.filter.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.columnsresize.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.selection.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.edit.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.export.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtree.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtreegrid.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdatatable.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxwindow.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtooltip.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtoolbar.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxcombobox.js') }}"></script>
<script src="{{ asset('/jqwidgets/jqxnavigationbar.js') }}"></script>
<script src="{{ asset('/jqwidgets/localization.js') }}"></script>
<script src="{{ asset('/plugins/fullscreen/jquery.fullscreen.js') }}"></script>