{{--<script src="{{ asset('/jqwidgets/jqxtabs.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxsplitter.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdata.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdata.export.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxlayout.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxribbon.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxpanel.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxexpander.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxscrollbar.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxbuttons.js?v=002') }}"></script>
<script src="{{ asset('/jqwidgets/jqxswitchbutton.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxinput.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtextarea.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxcheckbox.js?v=002') }}"></script>
<script src="{{ asset('/jqwidgets/jqxradiobutton.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxlistbox.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxnumberinput.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdropdownlist.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdropdownbutton.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.filter.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.columnsresize.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.selection.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.edit.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxgrid.export.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtree.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtreegrid.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxdatatable.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxwindow.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtooltip.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxtoolbar.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxcombobox.js?v=001') }}"></script>
<script src="{{ asset('/jqwidgets/jqxnavigationbar.js?v=001') }}"></script>--}}
